# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
references:

  container_config: &container_config
    docker:
      - image: node:8.10
    working_directory: ~/app

version: 2
jobs:

  build:
    <<: *container_config
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn build
  test:
    <<: *container_config
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install
      - checkout
      - run: yarn test

  # deploy:
  #   docker:
  #     - image: node:8.10
  #   working_directory:  /tmp/app
  #   steps:
  #     - run:
  #         name: Deploy Mater to Firebase
  #         command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  version: 2

  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build

  # -deploy:
  #   jobs:
  #     - build
  #     - deploy:
  #         requires:
  #           - build
  #         filters:
  #           branches:
  #             only: master


